name: SonarCloud monorepo

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: servico-aluguel
            path: servico-aluguel
            project_key: es220252_Engenharia-de-Software-II-Servico-Aluguel
          - name: servico-equipamento
            path: servico-equipamento
            project_key: es220252_Engenharia-de-Software-II-Servico-Equipamento
          - name: servico-externo
            path: servico-externo
            project_key: es220252_Engenharia-de-Software-II-Servico-Externo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        working-directory: ${{ matrix.service.path }}
        run: |
          poetry install --no-interaction --no-root

      - name: Run tests with coverage
        working-directory: ${{ matrix.service.path }}
        run: |
          poetry run pytest tests/ \
            --maxfail=1 -q \
            --cov-branch \
            --cov-report=xml:coverage.xml
          ls -la  # opcional, sÃ³ pra checar o coverage.xml no log

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ matrix.service.path }}
          args: >
            -Dsonar.projectKey=${{ matrix.service.project_key }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
